name: Discussion Comment Notification
on:
  discussion_comment:
    types: [created, edited]
  issue_comment:
    types: [created]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if mentioned or new discussion
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "discussion_comment" && "${{ github.event.comment.body }}" == *"@13982720426"* ]]; then
            echo "::set-output name=trigger::mention"
          elif [[ "${{ github.event_name }}" == "discussion" && "${{ github.event.action }}" == "created" ]]; then
            echo "::set-output name=trigger::new_discussion"
          else
            echo "::set-output name=trigger::none"
          fi

      - name: Send email notification for discussion actions
        if: github.event_name == 'discussion' || github.event_name == 'discussion_comment'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.event_name == 'discussion' && github.event.action == 'created' ? 'New Discussion Created' : 'New Comment on Discussion' }}
          html_body: |
            <p>A new action was performed on a discussion: <a href="${{ github.event.discussion.html_url }}">${{ github.event.discussion.title }}</a></p>
            <p>Action type: <b>${{ github.event_name }}</b></p>
            ${{ if github.event_name == 'discussion_comment' }}
            <p>Comment by: <b>${{ github.event.comment.user.login }}</b></p>
            <p>Comment content: <pre>${{ github.event.comment.body }}</pre></p>
            ${{ endif }}
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Notifications <${{ secrets.EMAIL_USERNAME }}>

      - name: Send success notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Run Succeeded"
          html_body: |
            <p>The GitHub Actions workflow ran successfully.</p>
            <p>Event: ${{ github.event_name }}</p>
            <p>Repository: ${{ github.repository }}</p>
            <p>Workflow: ${{ github.workflow }}</p>
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Notifications <${{ secrets.EMAIL_USERNAME }}>
